// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtD3rpbDWHaY4tpIzE8ZYydV9iobUw9RU',
    appId: '1:651939523948:web:566534b81fd99d6eec1749',
    messagingSenderId: '651939523948',
    projectId: 'ditonton-cdff6',
    authDomain: 'ditonton-cdff6.firebaseapp.com',
    storageBucket: 'ditonton-cdff6.firebasestorage.app',
    measurementId: 'G-LZWN47THLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArBNYEnIdA57rSOaAV9MuTCmsIeMKN6MI',
    appId: '1:651939523948:android:95e87e600a5edc38ec1749',
    messagingSenderId: '651939523948',
    projectId: 'ditonton-cdff6',
    storageBucket: 'ditonton-cdff6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGora3dqjKlNVcOFu_FjQElijl3r-DERs',
    appId: '1:651939523948:ios:c48a3e2c61377bbcec1749',
    messagingSenderId: '651939523948',
    projectId: 'ditonton-cdff6',
    storageBucket: 'ditonton-cdff6.firebasestorage.app',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
